M48
; DRILL file {KiCad 7.0.8} date Mon Nov  6 13:52:11 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-06T13:52:11-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0454
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1969
%
G90
G05
T1
X4.61Y-2.72
X5.62Y-4.76
X6.49Y-2.72
T2
X4.74Y-2.46
X6.36Y-2.46
X6.36Y-4.63
T0
M30
